sched/fair: Fix declaration after statement in sum_w_vruntime_add_paranoid()
This fixes the following warning:
../kernel/sched/fair.c:749:7: error: GCC does not allow variable declarations in for loop initializers before C99 [-Werror,-Wgcc-compat]
  749 |         for (struct rb_node *node = cfs_rq->tasks_timeline.rb_leftmost;
      |

Fixes: fdcc0ec41287 ("sched/fair: Increase weight bits for avg_vruntime")
Change-Id: I4d6dac639cb7a3432e7952aa82f5cbc47ba4da7a
Signed-off-by: angelomds42 <angelomds42@gmail.com>