fixup! UPSTREAM: bpf: Refactor sockmap redirect code so its easy to reuse
'sk_other' was introduced without use and the 'out_free' label was left unused.

Fixes:
../net/core/skmsg.c:743:15: error: unused variable 'sk_other' [-Werror,-Wunused-variable]
x743 |         struct sock *sk_other;
    |                      ^~~~~~~

../net/core/skmsg.c:752:1: error: unused label 'out_free' [-Werror,-Wunused-label]
752 | out_free:
    |

Change-Id: Ifb4c29f9979ddfda97ddbe0213c7db63a5af5334
Signed-off-by: angelomds42 <angelomds42@gmail.com>